### ISSUE TITLE
.Net SDK Repo: Naming, Runtimes, Publishing, etc

### ISSUE THREAD

**Issue by benjiro** [open-feature/research#10]
As suggested by @toddbaert I've created this discussion thread to kick off the conversations around getting the ball rolling on implementing the dotnet variant of the OpenFeature SDK. Things to consider

- Name of the project?
- What runtimes should we support? [.Net Framework](https://docs.microsoft.com/en-us/lifecycle/products/microsoft-net-framework ) | [.Net](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core)
- Who are the code-owners of this project?
- Project milestones, what release timeframe should we target?
- How will the project be published?

Anything else I missed feel free to add

**Comment by benjiro** [comment]
**Name of the project?** dotnet-sdk

**What runtimes should we support?** Suggest targeting netstandard2.0 so we a fully compatible back to .net framework 4.6.2. If we aren't going to bother supporting .net framework then I would suggest we just support .Net 6 onwards. .Net 3.1 is EOL soon
Who are the code-owners of this project? I'm willing to help out with the implementation and maintaining the dotnet SDK

**Project milestones, what release timeframe should we target?** Implement the current spec in full (API config, client, flag evaluation, hooks etc) and release a Alpha version of the SDK by the end of July

**How will the project be published?** Suggest using the standard tooling in the dotnet ecosystem which packages the library into a nuget bundle and publishes it to https://www.nuget.org/

**Comment by beeme1mr** [comment]
Hey @benjiro, thanks for putting this together and your interest in the project. I've gone ahead and created the repo. You can find it [here](https://github.com/open-feature/dotnet-sdk).

**Comment by benjiro** [comment]
Thanks @beeme1mr, I've create the initial project structure. https://github.com/open-feature/dotnet-sdk/pull/2

**Comment by toddbaert** [comment]
This sound good to me. I've also invited you to the project and reviewed your initial PR.

What do you think the published artifact should be called? `OpenFeature`? `OpenFeature.SDK`?

**Comment by benjiro** [comment]
@toddbaert Sorry for the late reply, been flat strap with work.

Thanks for the invite 😃 

Yea `OpenFeature` sounds pretty good to me, I think we should register the prefix asap. Probably makes sense to who ever has access to @openfeature.dev email to kick off the process. Are you able to handle this?

**Comment by beeme1mr** [comment]
I'm looking into this. You can track the progress in the issue below.

https://github.com/open-feature/community/issues/83

**Comment by toddbaert** [comment]
Thanks @beeme1mr

**Comment by beeme1mr** [comment]
Closing this now that the .net repo exists. Thanks for all your hard work @benjiro! It's very much appreciated.
