### ISSUE TITLE
[Proposal] Move all research into the repository

### ISSUE THREAD

**Issue by AlexsJones** [open-feature/research#19]
All research is currently in the form of a GitHub issue.
I propose that we backport all existing research into the repository and have all new research opened up as an RFC.

We could create a template `000-RFC-template.md` with a standard type of file structure that would allow contributors to open a PR up against a new item, incrementing the RFC e.g. `001-proposal-nginx.md`

**Comment by thomaspoignant** [comment]
Yes having an RFC format would help a lot.
And we can still discuss the research by opening a PR for this new RFC.
