### ISSUE TITLE
Create golang contrib "monorepo".

### ISSUE THREAD

**Issue by toddbaert** [open-feature/research#23]
This need not actually be a "monorepo", but we might want to create a single repo that holds a collection of go projects.

Definition of done:

- project created
- readme explaining what it is, how it's structured
- basic CI (not formal releases)

Might want to be done in conjunction with: https://github.com/open-feature/golang-sdk-contrib/issues/2

**Comment by james-milligan** [comment]
https://github.com/open-feature/golang-sdk-contrib
