### ISSUE TITLE
Node.JS Contrib Repo: Goals, Architecture, CI, etc

### ISSUE THREAD

**Issue by toddbaert** [open-feature/research#7]
We need to create a Node.JS repo that will serve as a home for various "extras" (ie: Hooks, Providers, etc). We likely want to use a monorepo (nx?). Things to consider:

- Publishing. Would each artifact have a published package?
- Code-ownership concerns
- Enforcing code quality and documentation
- Consistent versioning and releasing
- more?

Draw inspiration and insights from: https://github.com/open-telemetry/opentelemetry-js-contrib

**Comment by beeme1mr** [comment]
https://github.com/open-feature/node-sdk-contrib
